project_name: dval
release:
  github:
    owner: dvalai
    name: dval
builds:
  - id: dval
    goos:
    - linux
    - darwin
    goarch:
    - amd64
    - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: server.go
    binary: dval
    hooks: {}

archives:
  - id: dval
    builds:
      - dval
    format: tar.gz
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*

kos:
  - repository: ghcr.io/dvalai/dval
    main: server.go
    tags:
    - '{{.Version}}'
    - latest
    platforms:
    - linux/amd64
    - linux/arm64