name: test
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
          check-latest: true
          cache: true
      - run: go test ./... -coverprofile=c.out
      - run: sed -i "s%github.com/dvalai/%%" c.out
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        with:
          prefix: ${{ github.event.repository.name }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
