name: deploy
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --config deploy/.goreleaser.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}